#+STARTUP: indent
#+OPTIONS: toc:nil num:nil
#+TITLE: ECON 384 HW1
#+SETUPFILE: my_heading.org

#+LATEX: \linespread{1.5}

* Theory Recap
For a standard prospect $P=(w_-,w_+;p_-,p_+)$, the following hold:
- mean payoff: $\mathfrac{E}[P] = w_-p_- + w_+p_+ =: w$
  #+NAME: prospect_mean
  #+BEGIN_SRC python :exports none :var wm=0 :var wp=1 :var pm=0.75
  return wm*pm + wp*(1-pm)
  #+END_SRC
- Variance: since $p_-+p_+=1$,
          \[ \mathfrac{V}[P] = \mathfrac{E}[P^2] - \mathfrac{E}^2[P]
                             = w_-^2p_- + w_+^2p_+ - (w_-p_-+w_+p_+)^2
                             = p_-p_+(w_-^2+w_+^2)-2p_-p_+w_-w_+
                             = p_-p_+(w_+-w_-)^2
            \]
  #+NAME: prospect_var
  #+BEGIN_SRC python :exports none :var wm=0 :var wp=1 :var pm=0.75
  return pm*(1-pm)*(wp-wm)*(wp-wm)
  #+END_SRC


For an utility function $u=\alpha x^\beta$, $\alpha > 0,
\beta\in(0,1)$, the following hold:
- $u$ is strictly concave on $x\in(0,+\infty)$: $u'' =
  \alpha\beta(\beta-1)x^{\beta-2}<0$ if $\beta<1$
- A surety with the expected value $w$ matching that of the prospect
  has utility $v := u(w) = \alpha w^\beta = \alpha \left(w_-p_- + w_+p_+\right)^\beta$
- Jensen's inequality holds:
    \[ s := \mathfrac{E}[u(P)] = u(w_-)p_- + u(w_+)p_+
               = \alpha (w_-^\beta p_- + w_+^\beta p_+) < v := u(\mathfrac{E}(P)) = \alpha \left(w_-p_- + w_+p_+\right)^\beta
    \]
- The risk premium $\xi$ is given by
  \[ \xi := w - u^{-1}(s) =  w_-p_- + w_+p_+ - \Xi \]
  where the *certainty equivalent* is given by
  \[\Xi^\beta := w_-^\beta p_- + w_+^\beta p_+ =  w_+^\beta - (w_+^\beta - w_-^\beta) p_-\]
  - Jensen's inequality is equivalent to $\xi>0$
- The maximal bet that should be placed on the prospect is the certainty equivalent $\Xi$.
  - Note that the decision whether to place a bet or not *does not
    depend on $\alpha$*; In this particular example $\alpha$
    "cancels out"; but more generally the preference semi-ordering
    induced by a utility function does not change with scaling the
    function values. This is intuitively clear --- since the utility
    values are not directly observable any theory based on behaviour
    of the utility function must allow for e.g. changing the unit of
    measurement from e.g. 'utils' to 'kilo-utils' without changing the
    predictions about preferences.
  - Also note that by Jensen's inequality, $\beta\in(0,1)$ corresponds
    to a *risk-averse* actor: a wager equal to the expected value of
    the prospect will always be eschewed. Conversely, an insurance at
    actuarially fair premium will be accepted.
  - As the illustration shows, the actor will be indifferent between
    the prospect and placing a bet of amount $\Xi = w - \xi$
    #+NAME: bet_val
    #+BEGIN_SRC  python :exports none :var wm=0 :var wp=1 :var pm=0.75 :var beta=0.5
    return (pm * wm**beta + (1-pm)*wp**beta)**(1/beta)
    #+END_SRC

    #+NAME: risk_premium
    #+BEGIN_SRC python :exports none :var wm=0 :var wp=1 :var pm=0.75 :var beta=0.5 :var alpha=1
    return ( wm*pm + wp*(1-pm) - (pm * wm**beta + (1-pm)*wp**beta)**(1/beta) )
    #+END_SRC
  - Further, the value of maximum acceptable bet $\Upsilon =
    \left(w_+^\beta - (w_+^\beta - w_-^\beta) p_-\right)^{1/\beta}$ is
    at most $w_+$, and decreases towards $w_-$ as the probability
    $p_-$ of the 'downside' increases.
  - Maximum premium the actor would pay to `secure the state $w_+$' is $C := w_+ - \Xi$

** Illustration
#+begin_src latex :file choice-uncertainty.pdf :packages '(("" "tikz")) :border 1em :results raw
  % Define block styles
  \usetikzlibrary{shapes,arrows}
  \tikzstyle{astate} = [circle, draw, text centered, font=\footnotesize, fill=blue!25]
  \tikzstyle{rstate} = [circle, draw, text centered, font=\footnotesize, fill=red!25]
  \tikzset{  guide line/.style={dashed}
           , important line/.style={solid}
  }
  \resizebox{\columnwidth}{!}{
  \begin{tikzpicture}[yscale=1,xscale=0.5]
     % Axis
     \draw [->] (0,0) node [below] {0} -- (0,0) -- (10,0) node [below] {x};
     \draw [->] (0,0) node [below] {0} -- (0,0) -- (0,3.5) node [right] {u};
     \node [left] at (-0.2,3.3) {$\texttt{utility}$};
     \node [right] at (10.7,0.3) {$\texttt{payoff}$, \$};
     % utility vs payout
     \draw[domain=0:10,samples=100,smooth,variable=\x,blue] plot ({\x},{sqrt(\x)});

     % two outcomes of the prospect
     \coordinate (wm) at (1,0);
     \coordinate (um) at (0,1);
     \coordinate (wmum) at (1,1);
     \coordinate (wp) at (9,0);
     \coordinate (up) at (0,3);
     \coordinate (wpup) at (9,3);

     \draw [guide line] (wm) node[below] {$w_-$} -- (wmum);
     \draw [guide line] (wp) node[below] {$w_+$} -- (wpup);
     \draw [guide line] (um) node[left] {$u_-$} -- (wmum);
     \draw [guide line] (up) node[left] {$u_+$} -- (wpup);

     % w = 4 corresponds to p_- = 5/8
     \coordinate (w) at (4,0);
     \coordinate (s) at (0,2);
     \coordinate (ws) at (4,2);
     \coordinate (v)  at (0,7/4);
     \coordinate (wv) at (4,7/4);
     \coordinate (Xi) at (49/16,0);
     \coordinate (Xiv) at (49/16,7/4);

     \draw[guide line] (w) node[below] {$w$} -- (ws);
     \draw[guide line] (s) node[left]  {$s$} -- (ws);

     \draw [important line] (wmum) -- (wpup);

     \draw [guide line] (v) node[left] {$v$} -- (wv);
     \draw [guide line] (Xi) node[below] {$\Xi$} -- (Xiv);

     \draw [important line][red,thick] (Xiv) -- (wv) node[above,midway] {$\xi$};
  \end{tikzpicture}
  }

#+end_src
#+CAPTION: risk premium and maximal acceptable bet
#+LABEL: fig:tikz
#+RESULTS:

* Question 1
1. Basic descriptive stats: substitute values into the formulae above.

   | $w_-$, $ | $w_+$, $ | $p_-$ | $\mathfrac{E}[P]$, $ | $\mathfrac{V}[P]$, $ | $\Xi$, $ |
   | /        |          |       |                      |                      | <        |
   |----------+----------+-------+----------------------+----------------------+----------|
   | 50       |      650 |  0.75 |                200.0 |              67500.0 | 136.35   |
   #+TBLFM: $4='(org-sbe "prospect_mean" (wm $1) (wp $2) (pm $3))::$5='(org-sbe "prospect_var" (wm $1) (wp $2) (pm $3))'::$6='(org-sbe "bet_val" (wm $1) (wp $2) (pm $3))';%.2f

2. Risk-aversion: since $\beta=\frac{1}{2}<1$, the bet equal to the
   expected value of the prospect is to be *rejected*, as indeed any wager of more than $\Xi=136.35$.
3. See illustration
4. Plug in the numbers again. Note that the value of $\alpha$ is immaterial
   | $w_-$, $ | $w_+$, $ | $p_-$ | $\Upsilon$, $ | $\Xi$, $ |
   | /        |          |       |               | <        |
   |----------+----------+-------+---------------+----------|
   | 50       |     1400 |  0.75 |           200 | 214.84   |
   #+TBLFM: $5='(org-sbe "bet_val" (wm $1) (wp $2) (pm $3))';%.2f
   Now the bet of $\Upsilon<\Xi$ will have positive expected utility and should be *accepted*.
5. Again, plug in the numbers. Note that the value of $\alpha$ is still not relevant.
   | $w_-$, $ | $w_+$, $ | $p_-$ | $\mathfrac{E}[P]$, $ | $\Xi$, $ | $\xi$, $ |
   | /        |          |       |                      |          | <        |
   |----------+----------+-------+----------------------+----------+----------|
   | 50       |      650 |  0.75 |                200.0 |   136.35 | 63.65    |
   #+TBLFM: $4='(org-sbe "prospect_mean" (wm $1) (wp $2) (pm $3))::$5='(org-sbe "bet_val" (wm $1) (wp $2) (pm $3))';%.2f::$6='(org-sbe "risk_premium" (wm $1) (wp $2) (pm $3) (alpha $INVALID))';%.2f
   Note that the risk premium $\xi = w-\Xi = 200.00-136.35$, as expected.
6. Rearranging the formula for $\Xi$ as a function of $p_-$, we
   get that for $p_- \leq
   \frac{w_+^\beta-\Upsilon^\beta}{w_+^\beta-w_-^\beta}$ the bet
   should be accepted. For the numerical values in this example, we
   have
    #+NAME: pm_max
    #+BEGIN_SRC python :exports none :var wm=0 :var wp=1 :var bet=0.4 :var beta=0.5
    return (wp**beta-bet**beta)/(wp**beta-wm**beta)
    #+END_SRC

   | $w_-$, $ | $w_+$, $ | $\Upsilon$, $ | $p_-$ |
   | /        |          |               | <     |
   |----------+----------+---------------+-------|
   | 50       |      650 |           200 |  0.62 |
   #+TBLFM: $4='(org-sbe "pm_max" (wm $1) (wp $2) (bet $3));%.2f
   I.e. at $62\%$ or lower probability of a bad season, the bet
   becomes feasible.

* Question 2
1. From the point of view of the insurance company, the prospect is
   | $w_$, $1k | $w_+$, $1k | $p_-$ | $\mathfrac{E}[P]$, $1k |
   | /         |            |       | <                      |
   |-----------+------------+-------+------------------------|
   | -30       |          0 | 0.125 | -3.75                  |
   #+TBLFM: $4='(org-sbe "prospect_mean" (wm $1) (wp $2) (pm $3))

   The actuarially fair premium is therefore $3750; $4500 is *not*
   actuarially fair.

   For Jack, the prospect is
   | $w_$, $1k | $w_+$, $1k | $p_-$ | $\xi$, $1k |
   | /         |            |       | <          |
   |-----------+------------+-------+------------|
   | 10        |         40 | 0.125 | 10.94      |
   #+TBLFM: $4='(org-sbe "risk_premium" (wm $1) (wp $2) (pm $3) (alpha $1))';%.2f
   We see that the risk premium $\xi$ Jack is willing to pay is
   greater than the demanded insurance premium. He will therefore be
   willing to purchase insurance at this price.

2. We saw that the risk premium for this prospect under Jack's utility
   function is $10940. This is the maximum amount he will pay for
   insurance.

3. Combining the results in the Theory Recap secion, we have
   \[ \xi = w_+ - (w_+-w_-)p_- - \left(w_+^\beta - (w_+^\beta - w_-^\beta) p_-\right)^{1/\beta} \]

* Question 3

1. The prospect is identical to that of Question 1, part (a)
   | $w_-$, $ | $w_+$, $ | $p_-$ | $\mathfrac{E}[P]$, $ | $\mathfrac{V}[P]$, $ | $\Xi$, $ |
   | /        |          |       |                      |                      | <        |
   |----------+----------+-------+----------------------+----------------------+----------|
   | 50       |      650 |  0.75 |                200.0 |              67500.0 | 136.35   |
   #+TBLFM: $4='(org-sbe "prospect_mean" (wm $1) (wp $2) (pm $3))::$5='(org-sbe "prospect_var" (wm $1) (wp $2) (pm $3))'::$6='(org-sbe "bet_val" (wm $1) (wp $2) (pm $3))';%.2f

2. Same as in Question 1: no bet larger that $\Xi=136.35$ should be
   placed on this lottery. The cut-off value does *not* depend on
   $\alpha$.

3. Omitting further parts of the question which are identical to Question 1

4. We already know that the original lottery is infeasible, for any
   value of $\alpha>0$.  Diversification: For the alternative lottery,
   the payoffs for both states of the world at $t=1$ are given in the
   table below

   | time                           | t=0 | t=1; low oil | t=1; high oil |
   | /                              |   < |              |               |
   |--------------------------------+-----+--------------+---------------|
   | oil stock price, $             |  10 |         2.50 |         32.50 |
   | plastics stock price, $        |   5 |        25.00 |             1 |
   | nr. oil shares                 |  10 |           10 |            10 |
   | nr. plastics shares            |  20 |           20 |            20 |
   |--------------------------------+-----+--------------+---------------|
   | total value, oil stock, $      | 100 |        25.00 |        325.00 |
   | total value, plastics stock, $ | 100 |       500.00 |         20.00 |
   |--------------------------------+-----+--------------+---------------|
   | total payout                   |     |       525.00 |        345.00 |
   #+TBLFM: @5$2=@7$2/@3$2::@6$2=@8$2/@4$2::@7$3=@3$3*@5$3;%.2f::@8$3=@4$3*@6$3;%.2f::@>$3=vsum(@II..@III);%.2f::@7$4=@3$4*@5$4;%.2f::@8$4=@4$4*@6$4;%.2f::@>$4=vsum(@II..@III);%.2f

   The prospect corresponding to this alternative lottery is therefore
   | $w_-$, $ | $w_+$, $ | $p_-$ | $\mathfrac{E}[P]$, $ | $\Xi$, $ |
   | /        |          |       |                      | <        |
   |----------+----------+-------+----------------------+----------|
   | 345      |      525 |  0.25 |                480.0 | 476.47   |
   #+TBLFM: $4='(org-sbe "prospect_mean" (wm $1) (wp $2) (pm $3))::$5='(org-sbe "bet_val" (wm $1) (wp $2) (pm $3))';%.2f

   We see that it is feasible to bet any amount on this lottery up to $\Xi=476.47$, so the bet of $200 is certainly feasible.

* Question 4
- The CAPM discont rate $r_i= r_m\beta + r_f(1-\beta)$. For the example
  at hand, $100\%\cdot r_i= 4\% + 1.8\cdot (12\%-4\%) = 18.4\%$. The
  discounted payoff in period $t$ is given by $P(t)/r_i^t=P(t)/1.184^t$
  for $t=0,\ldots6$, and the NPV of the revenue stream under the CAPM
  rate is given as follows
  | period            |       0 |     1 |     2 |     3 |     4 |     5 |     6 | NPV    |
  | /                 |       < |       |       |       |       |       |       | <      |
  |-------------------+---------+-------+-------+-------+-------+-------+-------+--------|
  | payoff, $k        |    -200 |    20 |    30 |  40.5 |    50 |  60.5 |  60.5 |        |
  | discounted payoff | -200.00 | 16.89 | 21.40 | 24.40 | 25.44 | 26.00 | 21.96 | -63.91 |
  #+TBLFM: @>$2..@>$8=@3/(1.184^@1);%.2f::@>$>=vsum($2..$8);%.2f
  Since the NPV is negative, the investment should *not* be pursued.

- Recalculate for $\beta=0.20$: $100\%\cdot r_i = 4\% + 0.2\cdot(12\%-4\%) = 5.6\%$, so that
  | period            |       0 |     1 |     2 |     3 |     4 |     5 |     6 | NPV   |
  | /                 |       < |       |       |       |       |       |       | <     |
  |-------------------+---------+-------+-------+-------+-------+-------+-------+-------|
  | payoff, $k        |    -200 |    20 |    30 |  40.5 |    50 |  60.5 |  60.5 |       |
  | discounted payoff | -200.00 | 18.94 | 26.90 | 34.39 | 40.21 | 46.07 | 43.63 | 10.14 |
  #+TBLFM: @>$2..@>$8=@3/(1.056^@1);%.2f::@>$>=vsum($2..$8);%.2f
  Under the significantly lower CAPM discount rate of $5.6\%$, the NPV
  of the investment is positive; the investment is feasible.

- The discounted payoff for each period $t$ is given by $w_\pm\delta^t
  = w_\pm/1.05^t$, its utility is
  $u(w_\pm/1.05^t)=\sqrt{w_\pm)/1.05^{t/2}$, and the expected utility
  is therefore $u=\sum_{t=1}^6\,u(w_-\delta^t)p_- + u(w_+\delta^t)p_+ =


  | period $t$       | 1 | 2 | 3 | 4 | 5 | 6 |
  |------------------+---+---+---+---+---+---|
  | $w_-$, $k        |   |   |   |   |   |   |
  | $w_+$, $k        |   |   |   |   |   |   |
  |------------------+---+---+---+---+---+---|
  | discounted $w_-$ |   |   |   |   |   |   |
  | discounted $w_+$ |   |   |   |   |   |   |

* Question 5
- First, eliminate strategy $L$ since it is strictly dominated by
  $C$. Then, notice that strategy $D$ on the remaining outcomes is
  strictly dominated by strategy $U$, so is eliminated as well. What
  remains is a coordination game

  |   | C     | R    |
  | / | <     |      |
  |---+-------+------|
  | U | 12;5  | 7;7  |
  |---+-------+------|
  | M | 15;15 | 5;12 |
  |---+-------+------|

- Clearly a dominated strategy cannot yield a PSNE, and we should only
  search the reduced game for Nash equilibria. The PSNEs of the
  coordination game are $(U,R)$ and $(M,C)$: in either of these plays,
  no player has an incentive to unilaterally change his strategy. On
  the other hand, a play $(U,C)$ is not a Nash equilibrium since
  player 2 can unilaterally switch to strategy $R$ and increase his
  payoff. Similarly, $(M,R)$ is not a PSNE.

- For mixed Nash equilibria, suppose player 1 chooses $U$ with
  probability $p$, while player 2 chooses $C$ with probability $q$.
  Then the expected payoffs are $\mathfrac{E}[U] = 12q + 7(1-q)$ and
  $\mathfrac{E}[M] = 15q + 5(1-q)$ In equilibrium,
  $\mathfrac{E}[U]=\mathfrac{E}[M]$ so that $q=2/5$. Similarly,
  $5p+15(1-p)=7p+12(1-p)$, so that $p=3/5$

\newpage

* Question 7

- with $a=40, b=10$: Clearly the strategy where all countries choose
  the same level of effort $k\in S$ is a PSNE. Indeed, a unilateral
  increase of effort to level $K>k$ by any single player will only
  increase that player's cost, thus reducing its payoff by $b(K-k)>0$
  while keeping the payoff constant for the rest. A unilateral
  decrease in the effort level to $l<k$ will reduce the payoff for the
  player by $(a-b)(k-l)>0$, and for everyone else by $a(k-l)>0$. Since
  no individual unilateral deviation results in a higher payoff, this
  is an PSNE. Conversely, every strategy with effort levels not all
  equal is *not* an PSNE: suppose player $i$ is currently expending
  the more effort that anyone else (if such player cannot be found,
  then all are contributing equally). Then by decreasing its level of
  effort by one unit, it will save $b$ effort and thus increase its
  payoff by $b$.
- with $a=10, b=40$, the cost of maintaining effort for each
  individual player outweigh the benefits of reneging, and the only
  PSNE is all players choosing to contribute nothing. This is PSNE for
  the same reason as before: unilateral increase of effort only
  increases costs and brings no benefit. However, any non-zero level
  of effort by all players is no longer an PSNE: a unilateral decrease
  in effort from level $k$ to $l<k$ will result in *increase* in
  payoff by $(b-a)(k-l)$ for the reneging player.
- For the updated payoff function, any allocation of effort in which
  there is exactly one player expending maximal allowed effort while
  everyone else is expending zero is an PSNE: the player expending max
  effort cannot deviate to a lower level $l$ since it will be
  penalized by at least $(40-10)(10-l)$. Anyone else cannot increase
  their effort since they are already receiving maximal payoff when
  expending nothing. Conversely, any other allocation of effort is
  *not* PSNE: if no-one is expending maximal effort a player can
  increase their payoff by starting to do so, if any one player is
  expending the max effort, all other players should decrease their
  efforts to zero and increase their payoff by saving expense.
